# Generated by Django 5.2 on 2025-07-02 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp_request', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Barcode',
        ),
    ]
